# ... 你原本的設定 ...

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

external_links:
  target: "_blank"
  rel: "noopener noreferrer"

author:
  name: "周 寅彰 AKI（they/them）"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "嗨，可以叫我AKI就好。"
  links:
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.com/yenchung/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yenchung/"

# ... 以下維持原設定 ...
footer:
  links:
    - label: "Threads"
      icon: "fab fa-fw fa-threads"
      url: "https://www.threads.com/yenchung/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/yenchung/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
